name: vqa
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - bzip2=1.0.8=hda65f42_9
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libexpat=2.7.4=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_18
  - libgcc-ng=15.2.0=h69a702a_18
  - libgomp=15.2.0=he0feb66_18
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_18
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.10.19=h3c07f61_3_cpython
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.1.0
      - bitsandbytes==0.49.2
      - blinker==1.9.0
      - cachetools==6.2.6
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.4
      - datasets==4.5.0
      - dill==0.4.0
      - exceptiongroup==1.3.1
      - filelock==3.24.3
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - jinja2==3.1.6
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - langchain-core==1.2.14
      - langgraph==1.0.9
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.8
      - langgraph-sdk==0.3.8
      - langsmith==0.7.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - narwhals==2.16.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - orjson==3.11.7
      - ormsgpack==1.12.2
      - pandas==2.3.3
      - pillow==12.1.1
      - propcache==0.4.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pyarrow==23.0.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.14
      - referencing==0.37.0
      - regex==2026.2.19
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.3.3
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.54.0
      - sympy==1.14.0
      - tenacity==9.1.4
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.10.0
      - torchvision==0.25.0
      - tornado==6.5.4
      - tqdm==4.67.3
      - transformers==5.2.0
      - triton==3.6.0
      - typer==0.24.1
      - typer-slim==0.24.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uuid-utils==0.14.1
      - watchdog==6.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
